version: '3'

env:
  BUILD_PATH: ./build/queueverse
  DOCKER_REGISTRY: registry.wantia.app
  DOCKER_IMAGE: mwantia/queueverse
  DOCKER_VERSION: v0.0.3-alpha
  DOCKER_LATEST: alpha
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

tasks:
  setup:
    cmds:
      - go mod download
      - go mod tidy
  build:
    cmds:
      - task: setup
      - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-s -w -extldflags "-static"' -trimpath -o ${BUILD_PATH} ./cmd/queueverse/main.go
  run:
    cmds:
      - task: setup
      - go run cmd/queueverse/main.go agent --config ./tests/config.hcl
    ignore_error: true

  release:
    cmds:
      - task: setup
      - docker login ${DOCKER_REGISTRY}
      - docker buildx create --use --name multi-arch-builder || true
      - docker buildx build --push --platform ${DOCKER_PLATFORMS} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_VERSION} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_LATEST} .

  analyse:
    cmds:
      - task: build
      - gsa ${BUILD_PATH} --hide-sections
