version: '3'

env:
  DOCKER_REGISTRY: registry.wantia.app
  DOCKER_IMAGE: mwantia/prometheus
  DOCKER_VERSION: v0.0.1
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

tasks:
  local-build:
    dir: src
    aliases:
      - lbuild
    cmds:
      - go build -o ./build/prometheus ./cmd/prometheus/main.go
  local-run:
    dir: src
    aliases:
      - lrun
    cmds:
      - go run cmd/prometheus/main.go agent --config ./tests/config.hcl

  docker-setup:
    dir: src
    aliases:
      - dsetup
    cmds:
      - docker login registry.wantia.app
      - docker buildx create --use --name multi-arch-builder || true

  docker-build:
    dir: src
    aliases:
      - dbuild
    cmds:
      - task: docker-setup
      - docker buildx build --push --platform ${DOCKER_PLATFORMS} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_VERSION} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest .
