version: '3'

env:
  DOCKER_REGISTRY: registry.wantia.app
  DOCKER_IMAGE: mwantia/prometheus
  DOCKER_VERSION: v0.1.7
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

tasks:
  setup:
    dir: src
    cmds:
      - go mod download
      - go mod tidy
  build:
    dir: src
    cmds:
      - task: setup
      - go build -o ./build/prometheus ./cmd/prometheus/main.go
  run:
    dir: src
    cmds:
      - task: setup
      - go run cmd/prometheus/main.go agent --config ./tests/config.hcl
    ignore_error: true

  release:
    dir: src
    cmds:
      - task: setup
      - docker login ${DOCKER_REGISTRY}
      - docker buildx create --use --name multi-arch-builder || true
      - docker buildx build --push --platform ${DOCKER_PLATFORMS} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_VERSION} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest .

  analyse:
    dir: src
    cmds:
      - task: build
      - gsa ./build/prometheus --hide-sections
