global:
  scrape_interval: 30s

scrape_configs:
  - job_name: victoriametrics
    static_configs:
      - targets:
          - '127.0.0.1:8428'

  - job_name: asynqmon
    static_configs:
      - targets:
          - 'asynqmon:8000'