version: '3'

env:
  DOCKER_REGISTRY: registry.wantia.app
  DOCKER_IMAGE: mwantia/prometheus
  DOCKER_VERSION: v0.0.7
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

tasks:
  setup:
    cmds:
      - go mod download
      - go mod tidy
      - docker login ${DOCKER_REGISTRY}
      - docker buildx create --use --name multi-arch-builder || true
  build:
    cmds:
      - go build -o ./build/prometheus ./cmd/prometheus/main.go
  run:
    cmds:
      - go run cmd/prometheus/main.go agent --config ./tests/config.hcl

  release:
    cmds:
      - task: setup
      - docker buildx build --push --platform ${DOCKER_PLATFORMS} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_VERSION} -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest .
